services:
  mysql:
    image: mysql:8.0
    container_name: mysql_orcamento
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orcamento
    ports:
      - "3307:3306"
    volumes:
      - ./data/:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOSTS=mysql
      - UPLOAD_LIMIT=300M
    ports:
      - ${PMA_PORT:-8521}:80

  php:
    build: ./backend
    container_name: php_orcamento
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: next_orcamento
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - php